name: Govenor
favicon: null
layout_spectrum: 0.9847239886876196
typography_spectrum: 0.8143213030416518
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#ffffff'
    - '#dbcaa9'
    - '#4f4942'
    - '#847360'
  brandStrength: 0.5625
  lightness: 0.7597776520997286
  saturation: 0.2717342341784388
  rhythmicContrast: 0.5070092482492328
purpose: []
